services:

  broker-1:
    image: confluentinc/cp-kafka:7.5.1
    container_name: broker-1
    hostname: broker-1
    volumes:
      - broker1-data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf:ro
      - ./log4j.properties:/etc/confluent/docker/log4j.properties.template:ro
      - ./client_sasl_plaintext.properties:/etc/kafka/client_sasl_plaintext.properties:ro
    environment:
      # KRaft cluster setup
      CLUSTER_ID:       "KOwgCaI6R1qmYjz-drExVQ"
      KAFKA_NODE_ID:    1
      KAFKA_PROCESS_ROLES:        "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker-1:9093,2@broker-2:9093,3@broker-3:9093"
      # Listeners
      KAFKA_LISTENERS:              "SASL_PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS:   "SASL_PLAINTEXT://broker-1:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME:     "SASL_PLAINTEXT"
      # SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS:        "PLAIN"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      # JAAS
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      # LOG4J
      # KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/log4j.properties.template"

  broker-2:
    image: confluentinc/cp-kafka:7.5.1
    container_name: broker-2
    hostname: broker-2
    volumes:
      - broker2-data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf:ro
      - ./log4j.properties:/etc/confluent/docker/log4j.properties.template:ro
      - ./client_sasl_plaintext.properties:/etc/kafka/client_sasl_plaintext.properties:ro
    environment:
      CLUSTER_ID:       "KOwgCaI6R1qmYjz-drExVQ"
      KAFKA_NODE_ID:    2
      KAFKA_PROCESS_ROLES:        "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker-1:9093,2@broker-2:9093,3@broker-3:9093"
      KAFKA_LISTENERS:              "SASL_PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS:   "SASL_PLAINTEXT://broker-2:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME:     "SASL_PLAINTEXT"
      KAFKA_SASL_ENABLED_MECHANISMS:        "PLAIN"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      # LOG4J
      # KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/log4j.properties.template"

  broker-3:
    image: confluentinc/cp-kafka:7.5.1
    container_name: broker-3
    hostname: broker-3
    volumes:
      - broker3-data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf:ro
      - ./log4j.properties:/etc/confluent/docker/log4j.properties.template:ro
      - ./client_sasl_plaintext.properties:/etc/kafka/client_sasl_plaintext.properties:ro
    environment:
      CLUSTER_ID:       "KOwgCaI6R1qmYjz-drExVQ"
      KAFKA_NODE_ID:    3
      KAFKA_PROCESS_ROLES:        "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker-1:9093,2@broker-2:9093,3@broker-3:9093"
      KAFKA_LISTENERS:              "SASL_PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS:   "SASL_PLAINTEXT://broker-3:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME:     "SASL_PLAINTEXT"
      KAFKA_SASL_ENABLED_MECHANISMS:        "PLAIN"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      # LOG4J
      # KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/log4j.properties.template"

volumes:
  broker1-data:
  broker2-data:
  broker3-data:
