services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin-password-change-me
      DOCKER_INFLUXDB_INIT_ORG: ISIMA
      DOCKER_INFLUXDB_INIT_BUCKET: weather
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: super-admin-token-please-change-me
    volumes:
      - influxdb-data:/var/lib/influxdb2

  weather-pusher:
    build: ./pusher
    container_name: weather-pusher
    depends_on:
      - influxdb
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_ORG=ISIMA
      - INFLUX_BUCKET=weather
      - INFLUX_TOKEN=super-admin-token-please-change-me
      - PUSH_INTERVAL_SECONDS=5
      - MEASUREMENT=weather
      - FIELD_NAME=temperature_c
      - LOCATION_TAG=lab

  weather-watcher:
    build: ./watcher
    container_name: weather-watcher
    depends_on:
      - influxdb
    environment:
      - PYTHONUNBUFFERED=1        # logs immédiats
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_ORG=ISIMA
      - INFLUX_BUCKET=weather
      - INFLUX_TOKEN=super-admin-token-please-change-me
      - WATCH_INTERVAL_SECONDS=3  # polling
    restart: unless-stopped       # si jamais il crash

volumes:
  influxdb-data: